# Generated by Django 6.0.2 on 2026-02-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_groups_user_user_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "amount",
                    models.PositiveIntegerField(default=0, help_text="Сумма оплаты за обучение", verbose_name="Цена"),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Идентификатор сессии для проведения транзакции",
                        max_length=255,
                        null=True,
                        verbose_name="ID сессии",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Ссылка на оплату обучения. это не мошенники",
                        max_length=512,
                        null=True,
                        verbose_name="ссылка на оплату",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оплата",
                "verbose_name_plural": "Оплаты",
            },
        ),
    ]
