# Generated by Django 6.0.2 on 2026-02-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Введите ссылку на видео урока",
                max_length=1024,
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
